In [4]:
import pandas as pd

In [18]:
df = pd.read_csv("results.csv", sep = "|")

In [27]:
df.dropna(inplace=True)

In [28]:
df

image_name  comment_number  \
0       1000092795.jpg               0   
1       1000092795.jpg               1   
2       1000092795.jpg               2   
3       1000092795.jpg               3   
4       1000092795.jpg               4   
...                ...             ...   
158910   998845445.jpg               0   
158911   998845445.jpg               1   
158912   998845445.jpg               2   
158913   998845445.jpg               3   
158914   998845445.jpg               4   

                                                  comment  
0        Two young guys with shaggy hair look at their...  
1        Two young , White males are outside near many...  
2        Two men in green shirts are standing in a yard .  
3            A man in a blue shirt standing in a garden .  
4                 Two friends enjoy time spent together .  
...                                                   ...  
158910   A man in shorts and a Hawaiian shirt leans ov...  
158911   A young man hanging over the side of a boat ,...  
158912   A man is leaning off of the side of a blue an...  
158913   A man riding a small boat in a harbor , with ...  
158914   A man on a moored blue and white boat with hi...  

[158914 rows x 3 columns]

In [37]:
f = open("corpus.txt", "wt")

In [38]:
for s in df[' comment']:
    b= 
    b=b.lower()
    f.write(b[1:]+"\n")

In [39]:
f.close()

In [5]:
import string

In [6]:
from keras.preprocessing.text import Tokenizer

Using TensorFlow backend.


In [61]:
data = open('corpus.txt').read()
corpus = data.split("\n")

In [43]:
corpus

['two young guys with shaggy hair look at their hands while hanging out in the yard ',
 'two young  white males are outside near many bushes ',
 'two men in green shirts are standing in a yard ',
 'a man in a blue shirt standing in a garden ',
 'two friends enjoy time spent together ',
 'several men in hard hats are operating a giant pulley system ',
 'workers look down from up above on a piece of equipment ',
 'two men working on a machine wearing hard hats ',
 'four men on top of a tall structure ',
 'three men on a large rig ',
 'a child in a pink dress is climbing up a set of stairs in an entry way ',
 'a little girl in a pink dress going into a wooden cabin ',
 'a little girl climbing the stairs to her playhouse ',
 'a little girl climbing into a wooden playhouse ',
 'a girl going into a wooden building ',
 'someone in a blue shirt and hat is standing on stair and leaning against a window ',
 'a man in a blue shirt is standing on a ladder cleaning a window ',
 'a man on a ladder c

In [62]:
tokenizer = Tokenizer(num_words = wordcount, split=' ')
tokenizer.fit_on_texts(corpus)

In [32]:
data = []
for line in corpus:
    tokens = tokenizer.texts_to_sequences([line])[0]
    data.append(tokens)

In [36]:
maxLen = max([len(i) for i in data])
data2=tokens = tokenizer.texts_to_sequences(corpus)
data = pad_sequences(data2, maxlen=maxLen)

In [37]:
data

array([[   0,    0,    0, ...,    2,    3,  486],
       [   0,    0,    0, ...,   78,  192, 1420],
       [   0,    0,    0, ...,    2,    1,  486],
       ...,
       [   0,    0,    0, ...,    2,    3,   83],
       [   0,    0,    0, ...,    2,    3,   83],
       [   0,    0,    0, ...,    0,    0,    0]])

In [1]:
import numpy as np

In [34]:
data

array([[   0,    0,    0, ...,    2,    3,  486],
       [   0,    0,    0, ...,   78,  192, 1420],
       [   0,    0,    0, ...,    2,    1,  486],
       ...,
       [   0,    0,    0, ...,    2,    3,   83],
       [   0,    0,    0, ...,    2,    3,   83],
       [   0,    0,    0, ...,    0,    0,    0]])

In [5]:
from keras.preprocessing.sequence import pad_sequences

In [89]:
len(data[0])

78

In [90]:
wordcount

20011

In [7]:
import pickle

In [63]:
tokenize = open('tokenizer.pickle','wb')

In [64]:
pickle.dump(tokenizer,tokenize)

In [65]:
tokenize.close()

In [13]:
dumpy=open('captions.pickle','rb')

In [15]:
dumpy.close()

In [14]:
data=pickle.load(dumpy)

In [16]:
data

array([[   0,    0,    0, ...,    2,    3,  486],
       [   0,    0,    0, ...,   78,  192, 1420],
       [   0,    0,    0, ...,    2,    1,  486],
       ...,
       [   0,    0,    0, ...,    2,    3,   83],
       [   0,    0,    0, ...,    2,    3,   83],
       [   0,    0,    0, ...,    0,    0,    0]])

In [17]:
from keras.preprocessing.sequence import pad_sequences
from keras.layers import Embedding
from keras.layers import LSTM
from keras.layers import Dense
from keras.layers import Dropout
from keras import Sequential
from keras.layers import Bidirectional
from keras.optimizers import Adam
from keras import regularizers
from keras.layers import RepeatVector
from keras.layers import Input
import keras.utils as utils
from keras import Model

In [19]:
wordcount = 20011

In [20]:
maxLen=78

In [21]:
utils.to_categorical(data, num_classes=wordcount)

MemoryError: Unable to allocate 924. GiB for an array with shape (12395370, 20011) and data type float32

In [19]:
len(train_data)

158915

In [20]:
158915*78

12395370

In [50]:
autoencoder = Sequential()
autoencoder.add(Embedding(wordcount, 150, input_length=maxLen))#0
autoencoder.add(Bidirectional(LSTM(128, return_sequences = True)))
autoencoder.add(Dropout(0.3))
autoencoder.add(LSTM(128, return_sequences = True))
autoencoder.add(LSTM(64, return_sequences = True))
autoencoder.add(Dropout(0.3))
autoencoder.add(LSTM(32, return_sequences = True))
autoencoder.add(LSTM(16))#3
#decoder
autoencoder.add(RepeatVector(maxLen))
autoencoder.add(LSTM(32, return_sequences = True))
autoencoder.add(LSTM(64, return_sequences = True))
autoencoder.add(Dropout(0.3))
autoencoder.add(LSTM(128, return_sequences = True))
autoencoder.add(Bidirectional(LSTM(128, return_sequences = True)))
autoencoder.add(Dense(wordcount,activation='softmax'))

In [56]:
#2
autoencoder = Sequential()
autoencoder.add(Embedding(wordcount, 150, input_length=maxLen))#0
autoencoder.add(Bidirectional(LSTM(128, return_sequences = True)))
autoencoder.add(LSTM(128, return_sequences = True))
autoencoder.add(LSTM(64, return_sequences = True))
autoencoder.add(LSTM(32, return_sequences = True))
autoencoder.add(LSTM(8))#3
#decoder
autoencoder.add(RepeatVector(maxLen))
autoencoder.add(LSTM(32, return_sequences = True))
autoencoder.add(LSTM(64, return_sequences = True))
autoencoder.add(LSTM(128, return_sequences = True))
autoencoder.add(Bidirectional(LSTM(128, return_sequences = True)))
autoencoder.add(Dense(wordcount,activation='softmax'))

In [25]:
autoencoder.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, 78, 150)           3001650   
_________________________________________________________________
bidirectional_3 (Bidirection (None, 78, 256)           285696    
_________________________________________________________________
dropout_2 (Dropout)          (None, 78, 256)           0         
_________________________________________________________________
lstm_5 (LSTM)                (None, 32)                36992     
_________________________________________________________________
repeat_vector_2 (RepeatVecto (None, 78, 32)            0         
_________________________________________________________________
bidirectional_4 (Bidirection (None, 78, 256)           164864    
_________________________________________________________________
dense_2 (Dense)              (None, 78, 20011)        

In [59]:
opt = keras.optimizers.Adam(learning_rate=0.0001)
autoencoder.compile(optimizer=opt, loss='sparse_categorical_crossentropy',metrics=['accuracy'])

In [33]:
import numpy as np

In [29]:
import keras

In [57]:
checkpoint_filepath = 'tiny_unreg_caption_autoencoder_weights.{val_accuracy:.5f}.hdf5'
model_checkpoint_callback = keras.callbacks.ModelCheckpoint(
    filepath=checkpoint_filepath,
    save_weights_only=False,
    monitor='accuracy',
    mode='max',
    save_best_only=False)

In [60]:
history =autoencoder.fit(data, np.expand_dims(data, -1),epochs=20,
                shuffle=True,validation_split=0.2,callbacks=[model_checkpoint_callback])

Train on 127132 samples, validate on 31783 samples


KeyboardInterrupt: 

In [16]:
import tensorflow as tf

In [40]:
import keras

In [42]:
model = keras.models.load_model("caption_autoencoder.h5")

In [43]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, 78, 150)           3001650   
_________________________________________________________________
bidirectional_3 (Bidirection (None, 78, 256)           285696    
_________________________________________________________________
dropout_2 (Dropout)          (None, 78, 256)           0         
_________________________________________________________________
lstm_5 (LSTM)                (None, 64)                82176     
_________________________________________________________________
repeat_vector_2 (RepeatVecto (None, 78, 64)            0         
_________________________________________________________________
bidirectional_4 (Bidirection (None, 78, 256)           197632    
_________________________________________________________________
dense_2 (Dense)              (None, 78, 20011)        

In [21]:
autoencoder.save('caption_autoencoder.h5')

In [92]:
data.shape

(158915, 78)

In [23]:
encoder = Model(inputs=autoencoder.inputs, outputs=autoencoder.layers[3].output)
decoder_input = Input(autoencoder.layers[2].input_shape[1:])
decoder = decoder_input
for layer in autoencoder.layers[2:]:
    decoder = layer(decoder)
decoder = Model(inputs=decoder_input, outputs=decoder)

In [1]:
decoder.summary()

NameError: name 'decoder' is not defined

In [44]:
sentence = "here's a sample unseen sentence"
seq = tokenizer.texts_to_sequences([sentence])
pad_seq = pad_sequences(seq, 78)
sentence_vec = model.predict(pad_seq)[0]

In [33]:
sentence_vec

array([[9.99999762e-01, 5.99801106e-14, 2.26897711e-13, ...,
        4.35427146e-14, 4.40803603e-14, 4.49847611e-14],
       [9.99999881e-01, 4.65377215e-14, 1.76095087e-13, ...,
        1.04790789e-13, 1.03816376e-13, 1.06786914e-13],
       [1.00000000e+00, 3.77401256e-14, 1.35811813e-13, ...,
        6.97397191e-14, 6.91473923e-14, 7.04332426e-14],
       ...,
       [2.65931216e-04, 3.47184041e-03, 3.86394604e-05, ...,
        8.42641953e-07, 8.77327750e-07, 9.50372396e-07],
       [4.86558909e-03, 2.08828260e-06, 4.71988981e-09, ...,
        8.57868872e-06, 9.00159284e-06, 1.01110008e-05],
       [1.79217923e-02, 1.89435116e-06, 4.34857567e-11, ...,
        6.84007409e-06, 6.83338476e-06, 7.04360627e-06]], dtype=float32)

In [45]:
sentence_vec

array([[9.99999762e-01, 5.99801106e-14, 2.26897711e-13, ...,
        4.35427146e-14, 4.40803603e-14, 4.49847611e-14],
       [9.99999881e-01, 4.65377215e-14, 1.76095087e-13, ...,
        1.04790789e-13, 1.03816376e-13, 1.06786914e-13],
       [1.00000000e+00, 3.77401256e-14, 1.35811813e-13, ...,
        6.97397191e-14, 6.91473923e-14, 7.04332426e-14],
       ...,
       [2.65931216e-04, 3.47184041e-03, 3.86394604e-05, ...,
        8.42641953e-07, 8.77327750e-07, 9.50372396e-07],
       [4.86558909e-03, 2.08828260e-06, 4.71988981e-09, ...,
        8.57868872e-06, 9.00159284e-06, 1.01110008e-05],
       [1.79217923e-02, 1.89435116e-06, 4.34857567e-11, ...,
        6.84007409e-06, 6.83338476e-06, 7.04360627e-06]], dtype=float32)

In [2]:
import matplotlib.pyplot

In [3]:
matplotlib.pyplot.imshow(img)

NameError: name 'img' is not defined